spring.application.name=myApp
spring.flyway.enabled=false

# PostgreSQL pripojenie
spring.datasource.url=jdbc:postgresql://localhost:5432/rental_db
spring.datasource.username=matus
spring.datasource.password=batman77

# Hibernate - validate overí ?i entity sedí s DB tabu?kami
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=mojaAppTajnaHeslaKtoraMusiMat256BitovMinimalne12345678
jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
