spring.application.name=myApp
spring.flyway.enabled=false

# PostgreSQL pripojenie
spring.datasource.url=jdbc:postgresql://localhost:5432/rental_db
spring.datasource.username=postgres
spring.datasource.password=batman77

# Hibernate - validate overí ?i entity sedí s DB tabu?kami
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
