spring.application.name=myApp
spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/rental_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


jwt.secret=mojaAppTajnaHeslaKtoraMusiMat256BitovMinimalne12345678
jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true

cloudinary.cloud-name=dhqmyuawq
cloudinary.api-key=294283444173711
cloudinary.api-secret=Ivjw_NJ9m_h6zGoIF59ifW_0o4g